build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run

checks:
  javascript: true

filter:
  excluded_paths:
    - 'node_modules/*'
    - 'dist/*'
    - 'coverage/*'
    - 'test/*'
    - '*.config.*'
    - '*.d.ts'

coding_style:
  javascript: true
