build:
  environment:
    node: '22'
  
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    
    coverage:
      dependencies:
        override:
          - npm ci
      environment:
        node:
          version: '22'
      tests:
        override:
          - command: npm run test:coverage
            coverage:
              file: coverage/clover.xml
              format: clover

checks:
  javascript: true

filter:
  excluded_paths:
    - 'node_modules/*'
    - 'dist/*'
    - 'coverage/*'
    - 'test/*'
    - '*.config.*'
    - '*.d.ts'

coding_style:
  javascript: true

